version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "%(asctime)s [%(threadName)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default

root:
  level: WARN
  handlers: [console]

loggers:
  server.app:
    level: INFO
    handlers: [console]
    propagate: no

  server.rest_api:
      level: INFO
      handlers: [console]
      propagate: no

  server.managers.wifi_bands_manager:
    level: INFO
    handlers: [console]
    propagate: no

  server.interfaces.amx_usp_interface:
    level: INFO
    handlers: [console]
    propagate: no